@startuml D5700-Computer-Emulator

classDiagram
direction LR


class D5700 {
    -cpu: D5700CPU
    -ram: D5700Memory
    -rom: D5700Memory
    -keyboard: D5700Keyboard
    -screen: D5700Display
    -timer: D5700Timer
    +loadRom(path: String) void
    +run() void
}

class D5700Memory {
    -storage: byte[4096]
    +read(address: Number): byte
    +write(address: Number, value: byte) void
}

class D5700Keyboard {
    -keyPressed: boolean
    -keyValue: byte
    +isKeyPressed(): boolean
    +getKeyValue(): byte
    +setKeyPressed(pressed: boolean) void
    +setKeyValue(value: byte) void
}

class D5700Display {
    -display: byte[8][8]
    +draw(x: Number, y: Number, value: byte) void
    +clear() void
    +getDisplay(): byte[8][8]
}

class D5700Timer {
    -time: byte
    +setTime(time: byte) void
    +getTime(): byte
    +decrementTime() void
}

class D5700CPU {
    -programCounter: Number
    -timerRegister: Number
    -addressRegister: Number
    -memoryRegister: boolean
    -registers: byte[8]
    +start() void
    +executeNextInstruction() void
    +stop() void
    
    -add(registerX: Number, registerY: Number, registerZ: Number)
    -convertByteToAscii(registerX: Number, registerY: Number)
    -convertToBase10(register: Number)
    -draw(registerX: Number, registerY: Number, registerZ: Number)
    -jump(address: Number)
    -read(destinationRegister: Number)
    -readKeyboard(register: Number, address: Number)
    -readT(register: Number)
    -setA(address: Number)
    -setT(time: byte)
    -skipEqual(registerX: Number, registerY: Number)
    -skipNotEqual(registerX: Number, registerY: Number)
    -store(register: Number, value: byte)
    -subtract(registerX: Number, registerY: Number, registerZ: Number)
    -switchMemory()
    -write(sourceRegister: Number, address: Number)
}

@enduml